apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>APP TWO</title>
      </head>
      <body>
        <h1>APP TWO</h1>
      </body>
    </html>
