apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: nginx:bookworm
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-one
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-one
        configMap:
          name: app-one-html
