apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>APP ONE</title>
      </head>
      <body>
        <h1>APP ONE</h1>
      </body>
    </html>
