apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>APP THREE</title>
      </head>
      <body>
        <h1>APP THREE</h1>
      </body>
    </html>
